# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-13 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_carts', '0002_auto_20171110_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart_items', to='products.Product'),
        ),
    ]
