# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-10 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
